import { useState } from 'react';
import { ArrowUpRight, Download, ExternalLink, Search } from 'lucide-react';
import { sources } from '../content/science';
import { type Atlas, coordinates, useData } from '../lib/data';
import { DownloadLink } from './Shared';

export default function Methods() {
  const [search, setSearch] = useState('');
  const request = useData<Atlas>('/data/atlas.json');
  const filtered = sources.filter(source => `${source.title} ${source.organisation} ${source.scope}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="methods-page"><div className="page-intro"><h1>每一个解释，<br className="mobile-break" />都有来处。</h1><p>从原始数据到屏幕上的曲线，把方法和局限一起公开。</p></div>
    <div className="methods-introduction"><h2>我们在这里展示什么</h2><div><p>热浪解剖室是一份面向公众的气象数据探索工具。你可以观察真实历史记录，阅读有来源的物理解释，并在理想化实验中改变参数。</p><p>历史回放、文献解释和教学实验使用不同类型的证据。本站没有运行完整天气模式，没有计算新的气候变化归因，也没有完成拟议的长江区域论文研究。</p></div></div>
    <div className="evidence-table-wrap"><table className="evidence-table"><caption>三种内容，三种用途</caption><thead><tr><th>内容</th><th>依据</th><th>可以回答</th></tr></thead><tbody><tr><th>真实资料回放</th><td>ERA5再分析，经Open-Meteo取得</td><td>区域风温与代表格点在某个时刻怎样变化</td></tr><tr><th>形成机制解释</th><td>气象机构说明及原始研究</td><td>哪些物理过程可能参与、文献支持到哪里</td></tr><tr><th>理想化教学实验</th><td>公开方程及明确设定</td><td>在给定假设下，改变参数会怎样影响结果</td></tr></tbody></table></div>
    <section className="method-block"><div className="section-heading"><h2>数据覆盖与口径</h2><span className="small muted">数据版本 2026-09-27</span></div><div className="method-columns"><div><h3>六个地点，二十年日记录</h3><p>2006—2025年逐日最高、最低2米气温，共43,830日。每个点位采用1991—2020年完整参考期，按照同季节31日窗口计算均值和P90阈值。</p><p>三个人工选择的回放窗口共1,152小时。世界案例页收录12个精选事件，未建立全球全量热浪目录。</p></div><div><h3>网格、时钟与单位</h3><p>地名对应附近ERA5格点，不能当作城市气象站纪录。日值按UTC日聚合；回放的当地时间选项仅转换小时标签。</p><p>气温是°C，辐射是W/m²，土壤体积含水量是m³/m³。短波辐射表示前一小时平均，降水表示前一小时累计。</p></div></div>
    {request.data && <div className="table-scroll"><table className="location-table"><thead><tr><th>地点</th><th>请求坐标</th><th>返回格点</th><th>逐日表格</th></tr></thead><tbody>{request.data.cities.map(city => <tr key={city.id}><th>{city.name}</th><td>{coordinates(city.requestedLocation)}</td><td>{coordinates(city.gridLocation)}</td><td><a href={city.csvUrl} download>CSV <Download size={13} /></a></td></tr>)}</tbody></table></div>}
    <p className="small muted">悉尼样本为沿海格点，格点海拔为0米，尤其不能用作悉尼市区或机场的极值纪录。</p></section>
    <section className="method-block"><h2>把风温放回地图</h2><p>重庆—四川、巴黎周边、波特兰周边的有限区域共1,475个节点、559,200个格点小时；网格间距0.25°。地图按2米气温着色，以10米风显示流向，并与下方曲线共用同一时间轴。</p><p>风分量由API风速和来向转换，保留原始精度限制。连续画面经过空间插值，点击读取原始格点；放大不增加数据分辨率。固定12—42°C色标在两端饱和，蓝色不是气候异常。粒子在选中小时的固定风场中流动，时间切换后重新播种，不能当作气块历史轨迹或完整热量收支。</p><div className="download-strip"><DownloadLink href="/regional-methods.md">区域数据、动画与地图说明</DownloadLink><a className="inline-link" href="#replay?case=chongqing2022">打开真实案例地图 <ArrowUpRight size={14} /></a></div></section>
    <section className="method-block"><h2>自定义高温过程</h2><p>日最高温严格超过当地日历P90阈值，并连续至少3个UTC日，记为一次点位高温过程。暖季预设北半球5—9月、南半球11—3月；过程之间的间断日不合并。</p><p>这是可重复的探索性定义，不是当地官方预警标准。预设月份可能遗漏其他季节的高温；参考期与展示年份部分重叠，未做标准气候指数中的样本内百分位自举校正。本站不据此报告显著趋势或风险增加倍数。</p><div className="download-strip"><DownloadLink href="/data/annual-summary.csv">年度汇总</DownloadLink><DownloadLink href="/data/sources.csv">原始请求与来源</DownloadLink><DownloadLink href="/data/validation.json">数据校验记录</DownloadLink><DownloadLink href="/data/download-manifest.csv">文件SHA-256</DownloadLink><DownloadLink href="/data-methods.md">完整数据说明</DownloadLink><DownloadLink href="/downloads/heat-atlas-source.zip">网站与处理代码</DownloadLink></div></section>
    <section className="method-block"><h2>验证做到了哪一步</h2><div className="method-columns"><div><h3>已经核对</h3><p>原始输入哈希、连续日期与时刻、缺失值、最高最低温次序、单位、格点一致性，以及公开JSON和CSV与原始记录的逐值对应。另行检查分位数、严格阈值和最短持续时间的边界。</p></div><div><h3>仍有边界</h3><p>这些检查验证数据处理过程，不能证明再分析在所有地方完全准确。本站没有完整区域热收支、反事实模式或居民行为实验，也不提供个人健康诊断。</p><p>NOAA机场六日资料单独提供，采用站点观测日且缺少完整质量标记，未直接与ERA5的UTC日计算误差。</p><DownloadLink href="/data/noaa-portland-airport-2021.csv">NOAA站点样本</DownloadLink></div></div></section>
    <section className="method-block"><h2>粒子热场：可检查的理想实验</h2><p>二维封闭箱中的温度、速度与浮力相互耦合。模型采用无量纲 Boussinesq 近似、保守温度输送与压力投影；示踪粒子按当地流速移动，按当地温度异常着色。显示密度与物理网格独立。</p><p>物理测试覆盖静止、纯扩散、暖升冷降、热异常积分、边界、重置，以及时间步和网格加密后的热团重心收敛趋势。这些检查不构成真实热浪模式或完整湍流模拟的验证。模型不包含辐射、压缩和陆面过程。</p><div className="download-strip"><DownloadLink href="/thermal-methods.md">模型、参数与验证说明</DownloadLink><a className="inline-link" href="#particles">打开粒子热场 <ArrowUpRight size={14} /></a></div></section>
    <section className="method-block" id="sources"><div className="section-heading"><h2>来源书架</h2><label className="source-search"><Search size={16} /><span className="sr-only">搜索来源</span><input type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="搜索机构、机制或事件" /></label></div><p className="small muted">官方说明、数据产品与原始论文分别标明。核查范围不等于对每篇全文逐页审读。</p><div className="source-register">{filtered.map(source => <article key={source.id}><div className="source-kind">{source.kind === 'official' ? '官方资料' : source.kind === 'paper' ? '原始论文' : '数据产品'}</div><div><a className="source-title" href={source.url} target="_blank" rel="noreferrer">{source.title}<ArrowUpRight size={17} /></a><p>{source.organisation}</p><details><summary>核查范围与限制</summary><p>{source.scope}</p><p>{source.limitation}</p><small>核查日期 {source.checkedAt}</small></details></div></article>)}{!filtered.length && <p className="empty-state">没有匹配的来源。可以试试 NASA、ERA5 或热浪。</p>}</div></section>
    <section className="method-block attribution"><h2>数据署名与更新</h2><p><a href="/third-party-notices.txt" download>下载开源依赖许可证全文</a> · <a href="https://github.com/AlfWuxy/heatwave-atlas-lab" target="_blank" rel="noreferrer">查看公开代码与复现方法</a></p><p>气象数据：ECMWF / Copernicus ERA5，经 <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo<ExternalLink size={12} /></a> 提供；Open-Meteo API数据按 <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a> 署名。世界底图：Natural Earth，经world-atlas整理，属于公有领域。区域地图由MapLibre绘制，底图 © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a>，是当前地理背景。地形机制插画为AI生成的通用示意。外部论文与报告保留各自权利，本站使用简要释义和原文链接。</p><p>数据保留下载日期与哈希；产品后续修订可能产生不同数值。代码、内容或资料变化时会更新发布版本。当前版本：1.0.0 · 2026-09-27。</p></section>
  </section>;
}
