import { useState } from 'react';
import { ArrowUpRight, Download, ExternalLink, Search } from 'lucide-react';
import { sources } from '../content/science';
import { type Atlas, type CaseMeta, coordinates, useData } from '../lib/data';
import { DownloadLink } from './Shared';

export default function Methods() {
  const [search, setSearch] = useState('');
  const request = useData<Atlas>('/data/atlas.json');
  const extended = useData<{ cases: CaseMeta[]; status: string }>('/data/extended-cases.json');
  const expansion = useData<{ cases: CaseMeta[]; status: string }>('/data/expansion-cases.json');
  const addedCases = extended.data?.cases ?? [];
  const expandedCases = expansion.data?.cases ?? [];
  const expandedHours = expandedCases.reduce((sum, item) => sum + item.hours, 0);
  const addedHours = addedCases.reduce((sum, item) => sum + item.hours, 0);
  const eventSources = [...addedCases, ...expandedCases].flatMap(item => (item.eventEvidence ?? []).map((source, i) => ({
    id: `${item.id}-${i}`, title: source.title, organisation: source.organisation, url: source.url,
    kind: /Attribution|Geophysical|Universidade|UFRJ|Atmosphere/.test(source.organisation) ? 'paper' : /Defense Council|NRDC/.test(source.organisation) ? 'firstparty' : 'official', checkedAt: '2026-10-02',
    scope: `已核对与${item.title}相关的正文、日期和范围；详见对应批次的方法说明。`,
    limitation: '事件报告与本站点位再分析具有不同范围；未重新复现归因或健康影响估计。',
  })));
  const register = [...sources, ...eventSources].filter((item, index, all) => all.findIndex(source => source.url === item.url) === index);
  const filtered = register.filter(source => `${source.title} ${source.organisation} ${source.scope}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="methods-page"><div className="page-intro"><h1>每一个解释，<br className="mobile-break" />都有来处。</h1><p>从原始数据到屏幕上的曲线，把方法和局限一起公开。</p></div>
    <div className="methods-introduction"><h2>我们在这里展示什么</h2><div><p>热浪解剖室是一份面向公众的气象数据探索工具。你可以观察真实历史记录，阅读有来源的物理解释，并在理想化实验中改变参数。</p><p>历史回放、文献解释和教学实验使用不同类型的证据。本站没有运行完整天气模式，没有计算新的气候变化归因，也没有完成拟议的长江区域论文研究。</p></div></div>
    <div className="evidence-table-wrap"><table className="evidence-table"><caption>三种内容，三种用途</caption><thead><tr><th>内容</th><th>依据</th><th>可以回答</th></tr></thead><tbody><tr><th>真实资料回放</th><td>ERA5再分析，经Open-Meteo取得</td><td>区域风温与代表格点在某个时刻怎样变化</td></tr><tr><th>形成机制解释</th><td>气象机构说明及原始研究</td><td>哪些物理过程可能参与、文献支持到哪里</td></tr><tr><th>理想化教学实验</th><td>公开方程及明确设定</td><td>在给定假设下，改变参数会怎样影响结果</td></tr></tbody></table></div>
    <section className="method-block"><div className="section-heading"><h2>数据覆盖与口径</h2><span className="small muted">数据更新 2026-10-02</span></div><div className="method-columns"><div><h3>六个地点，二十年日记录</h3><p>2006—2025年逐日最高、最低2米气温，共43,830日。每个点位采用1991—2020年完整参考期，按照同季节31日窗口计算均值和P90阈值。</p><p>原有三个人工选择的回放窗口共1,152小时；另有第一批十地与第二批三十地的高温观察窗，共43个地点可供探索。多个地点可能经历同一场区域热浪，不能把城市数作为独立事件样本数。世界案例页保留12个文献事件故事，另有可直接操作的资料目录；未建立全球全量热浪目录。</p></div><div><h3>网格、时钟与单位</h3><p>地名对应附近ERA5格点，不能当作城市气象站纪录。日值按UTC日聚合；回放的当地时间选项转换小时标签；新增夜间模块另按当地18:00—次日05:59窗口内的完整小时采样计算。</p><p>气温是°C，辐射是W/m²，土壤体积含水量是m³/m³。短波辐射表示前一小时平均，降水表示前一小时累计。</p></div></div>
    {request.data && <div className="table-scroll"><table className="location-table"><thead><tr><th>地点</th><th>请求坐标</th><th>返回格点</th><th>逐日表格</th></tr></thead><tbody>{request.data.cities.map(city => <tr key={city.id}><th>{city.name}</th><td>{coordinates(city.requestedLocation)}</td><td>{coordinates(city.gridLocation)}</td><td><a href={city.csvUrl} download>CSV <Download size={13} /></a></td></tr>)}</tbody></table></div>}
    <p className="small muted">悉尼样本为沿海格点，格点海拔为0米，尤其不能用作悉尼市区或机场的极值纪录。</p></section>
    <section className="method-block"><h2>把风温放回地图</h2><p>重庆—四川、巴黎周边、波特兰周边的有限区域共1,475个节点、559,200个格点小时；网格间距0.25°。地图按2米气温着色，以10米风显示流向，并与下方曲线共用同一时间轴。</p><p>风分量由API风速和来向转换，保留原始精度限制。连续画面经过空间插值，点击读取原始格点；放大不增加数据分辨率。固定12—42°C色标在两端饱和，蓝色不是气候异常。粒子在选中小时的固定风场中流动，时间切换后重新播种，不能当作气块历史轨迹或完整热量收支。</p><div className="download-strip"><DownloadLink href="/regional-methods.md">区域数据、动画与地图说明</DownloadLink><a className="inline-link" href="#replay?case=chongqing2022">打开真实案例地图 <ArrowUpRight size={14} /></a></div></section>
    <section className="method-block"><h2>十处新地点，同一套可追溯资料</h2><p>伦敦、凤凰城、墨尔本、东京、达卡、卡拉奇、莫斯科、马德里、布宜诺斯艾利斯与阿加迪尔。每地选择16—31天的UTC观察窗；原值气温、相对湿度、海平面气压、云量、短波、10米风速/来向、两层土壤水分与降水，共十个小时字段。</p><p>{extended.data ? `当前资料索引包含${addedCases.length}个新增案例、${addedHours.toLocaleString()}个单点小时。每例25个规则格点，共${(addedHours * 25).toLocaleString()}个区域格点小时。` : '资料索引加载后显示实际数量。'}每个区域跨度1°×1°、间距0.25°；这里的完整指指定窗口与字段齐备，不代表完整热量收支、整场热浪范围或新的独立气候模式。</p><p>固定ERA5、最近格点、关闭高程降尺度。代表曲线与区域中心的气温及风逐值核对。原始土壤小负值保留并标记，不能作为真实负含水量解释；缺测检查通过不等于所有数值物理有效。凤凰城与莫斯科窗口截取长事件的一部分。</p><div className="download-strip"><DownloadLink href="/data/extended-cases.json">十地资料索引</DownloadLink><DownloadLink href="/extended-methods.md">十地来源、质量标记与方法</DownloadLink><a className="inline-link" href="#world">选择一个地点 <ArrowUpRight size={14} /></a></div></section>
    <section className="method-block"><h2>再走进三十处高温现场</h2><p>新增美洲10地、欧洲10地，以及亚洲、非洲和大洋洲10地。覆盖高纬度、沿海、内陆和不同季节；目录支持地区、年份与地名联合筛选。每地为16—20天的人工UTC观察窗，包含相同的十项单点字段与5×5风温格网。</p><p>{expansion.data ? `这一批已提供${expandedCases.length}个案例、${expandedHours.toLocaleString()}个单点小时与${(expandedHours * 25).toLocaleString()}个区域格点小时。` : '三十地资料索引加载后显示实际数量。'}西雅图、温哥华与原波特兰案例共享2021年北美西北事件；南欧的多个城市也可能共享同一轮大尺度过程。这里比较地点经历，不将它们当作相互独立的归因样本。</p><p>事件说明主要来自各国气象机构或原始研究；艾哈迈达巴德另采用热行动计划参与方的原始项目记录，仅作为高温警报情境。逐例列出阅读范围与观察窗选择。新加坡、里斯本等条目明确称高温观察过程，未声称满足当地所有官方热浪判据。筛选仅帮助浏览，默认年份排序不表示影响或强度排名。</p><div className="download-strip"><DownloadLink href="/data/expansion-cases.json">三十地资料索引</DownloadLink><DownloadLink href="/data/expansion-validation.json">三十地完整性校验</DownloadLink><DownloadLink href="/expansion-methods.md">逐例来源与数据方法</DownloadLink><a className="inline-link" href="#world">浏览全球地点 <ArrowUpRight size={14} /></a></div></section>
    <section className="method-block"><h2>欧洲2019：气温与土地的两个月</h2><p>巴黎、图卢兹、布鲁塞尔、法兰克福附近四个ERA5格点，2019年6月1日至7月31日共5,856个格点小时、46,848个数值，缺测为零。包含2米气温、0—7cm与7—28cm土壤体积含水率、降水、向下短波、10米风与云量；固定ERA5模型并禁用高程降尺度。</p><p>四点不代表欧洲区域均值。动态场景用原值编码风、光、雨和土色，是变量示意；没有运行地表热收支模型。土壤水分不是饱和百分比，没有气候距平或干旱分类。短波和降水对应时间戳结束的前一小时；完整日积分需要次日00时，当前包不含8月1日00时。</p><p>新增A/B比较固定格点和色标，差值是两个小时之差。夜间统计采用当地18:00—次日05:59内的12个连续小时采样，仅有12小时后的晨间采样才显示端点降幅；这不是UTC日最低、天文夜间或健康恢复指标。</p><div className="download-strip"><DownloadLink href="/data/europe2019-mechanism.json">四点完整资料</DownloadLink><DownloadLink href="/europe-methods.md">欧洲数据与画面说明</DownloadLink><a className="inline-link" href="#mechanism">打开地表记忆 <ArrowUpRight size={14} /></a></div></section>
    <section className="method-block"><h2>自定义高温过程</h2><p>日最高温严格超过当地日历P90阈值，并连续至少3个UTC日，记为一次点位高温过程。暖季预设北半球5—9月、南半球11—3月；过程之间的间断日不合并。</p><p>这是可重复的探索性定义，不是当地官方预警标准。预设月份可能遗漏其他季节的高温；参考期与展示年份部分重叠，未做标准气候指数中的样本内百分位自举校正。本站不据此报告显著趋势或风险增加倍数。</p><div className="download-strip"><DownloadLink href="/data/annual-summary.csv">年度汇总</DownloadLink><DownloadLink href="/data/sources.csv">原始请求与来源</DownloadLink><DownloadLink href="/data/validation.json">数据校验记录</DownloadLink><DownloadLink href="/data/download-manifest.csv">文件SHA-256</DownloadLink><DownloadLink href="/data-methods.md">完整数据说明</DownloadLink><DownloadLink href="/downloads/heat-atlas-source.zip">网站与处理代码</DownloadLink></div></section>
    <section className="method-block"><h2>验证做到了哪一步</h2><div className="method-columns"><div><h3>已经核对</h3><p>原始输入哈希、连续日期与时刻、缺失值、最高最低温次序、单位、格点一致性，以及公开JSON和CSV与原始记录的逐值对应。另行检查分位数、严格阈值和最短持续时间的边界。</p></div><div><h3>仍有边界</h3><p>这些检查验证数据处理过程，不能证明再分析在所有地方完全准确。本站没有完整区域热收支、反事实模式或居民行为实验，也不提供个人健康诊断。</p><p>NOAA机场六日资料单独提供，采用站点观测日且缺少完整质量标记，未直接与ERA5的UTC日计算误差。</p><DownloadLink href="/data/noaa-portland-airport-2021.csv">NOAA站点样本</DownloadLink></div></div></section>
    <section className="method-block"><h2>粒子热场：可检查的理想实验</h2><p>二维封闭箱中的温度、速度与浮力相互耦合。模型采用无量纲 Boussinesq 近似、保守温度输送与压力投影；示踪粒子按当地流速移动，按当地温度异常着色。显示密度与物理网格独立。</p><p>物理测试覆盖静止、纯扩散、暖升冷降、热异常积分、边界、重置，以及时间步和网格加密后的热团重心收敛趋势。这些检查不构成真实热浪模式或完整湍流模拟的验证。模型不包含辐射、压缩和陆面过程。</p><div className="download-strip"><DownloadLink href="/thermal-methods.md">模型、参数与验证说明</DownloadLink><a className="inline-link" href="#particles">打开粒子热场 <ArrowUpRight size={14} /></a></div></section>
    <section className="method-block" id="sources"><div className="section-heading"><h2>来源书架</h2><label className="source-search"><Search size={16} /><span className="sr-only">搜索来源</span><input type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="搜索机构、机制或事件" /></label></div><p className="small muted">官方说明、数据产品与原始论文分别标明。核查范围不等于对每篇全文逐页审读。</p><div className="source-register">{filtered.map(source => <article key={source.id}><div className="source-kind">{source.kind === 'official' ? '官方资料' : source.kind === 'paper' ? '原始研究' : source.kind === 'firstparty' ? '项目方原始记录' : '数据产品'}</div><div><a className="source-title" href={source.url} target="_blank" rel="noreferrer">{source.title}<ArrowUpRight size={17} /></a><p>{source.organisation}</p><details><summary>核查范围与限制</summary><p>{source.scope}</p><p>{source.limitation}</p><small>核查日期 {source.checkedAt}</small></details></div></article>)}{!filtered.length && <p className="empty-state">没有匹配的来源。可以试试 NASA、ERA5 或热浪。</p>}</div></section>
    <section className="method-block attribution"><h2>数据署名与更新</h2><p><a href="/third-party-notices.txt" download>下载开源依赖许可证全文</a> · <a href="https://github.com/AlfWuxy/heatwave-atlas-lab" target="_blank" rel="noreferrer">查看公开代码与复现方法</a></p><p>气象数据：ECMWF / Copernicus ERA5，经 <a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Open-Meteo<ExternalLink size={12} /></a> 提供；Open-Meteo API数据按 <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a> 署名。世界底图：Natural Earth，经world-atlas整理，属于公有领域。区域地图由MapLibre绘制，底图 © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a>，是当前地理背景。地形机制插画为AI生成的通用示意。外部论文与报告保留各自权利，本站使用简要释义和原文链接。</p><p>数据保留下载日期与哈希；产品后续修订可能产生不同数值。代码、内容或资料变化时会更新发布版本。当前版本：1.2.0 · 2026-10-02。</p></section>
  </section>;
}
